"""bugfix

Revision ID: 8c12c9462efd
Revises: cb7abe0663ae
Create Date: 2025-06-24 15:36:24.510912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c12c9462efd'
down_revision = 'cb7abe0663ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_type_category'), type_='unique')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_type_category'), ['type_category'])

    # ### end Alembic commands ###
