"""bugfix

Revision ID: e79efa67a678
Revises: 888f59ddd1dd
Create Date: 2025-06-24 11:30:53.282496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79efa67a678'
down_revision = '888f59ddd1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
